version: '3.1'

services:
  db:
    image: postgres
    container_name: rest-go-api-db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    ports:
      - 5432:5432
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
